version: '3'
services:

# Org1 #####################################

  um_ca:
    build: ./um/ca/
    hostname: ca
    domainname: um.es
    volumes:
        - um-certs:/certs
    network_mode: none

  um_crl:
    image: halverneus/static-file-server
    hostname: crl
    domainname: um.es
    environment:
        - PORT=80
    volumes:
        - lego_ca:/web
    networks:
        red1:
            aliases:
                - crl.um.es
            ipv4_address: 192.168.251.99

  um_snmp:
    build: ./um/snmp/
    hostname: snmp
    domainname: um.es
    networks:
        red1:
            aliases:
                - snmp.um.es
            ipv4_address: 192.168.251.100

  um_db:
    image: postgres:10-alpine
    hostname: db
    domainname: um.es
    environment:
        - POSTGRES_PASSWORD=owncloud
    networks:
        red1:
            aliases:
                - db.um.es
            ipv4_address: 192.168.251.4

  um_radius:
    build: ./um/radius/
    hostname: radius
    domainname: um.es
    depends_on:
        - "um_snmp"
        - "um_openldap"
    networks:
        red1:
            aliases:
                - radius.um.es
            ipv4_address: 192.168.251.3

  um_owncloud:
    build: ./um/owncloud
    hostname: owncloud
    domainname: um.es
    volumes:
        - um-certs-owncloud:/etc/apache2/keys/
    depends_on:
        - "um_db"
        - "um_openldap"
        - "um_crl"
        - "um_snmp"
    links:
        - um_db:owncloud-db
    ports:
        - "80:80"
        - "443:443"
    environment:
        - OWNCLOUD_DB_HOST=db.um.es
        - OWNCLOUD_DB_TYPE=pgsql
        - OWNCLOUD_DB_NAME=owncloud
        - OWNCLOUD_DB_USERNAME=postgres
        - OWNCLOUD_DB_PASSWORD=owncloud
        - OWNCLOUD_ADMIN_USERNAME=owncloud
        - OWNCLOUD_ADMIN_PASSWORD=owncloud
        - OWNCLOUD_VOLUME_CERTS=/etc/apache2/keys/
    networks:
        red1:
            aliases:
                - owncloud.um.es
            ipv4_address: 192.168.251.5

  um_openldap:
    build: ./um/openldap/
    hostname: ldap
    domainname: um.es
    depends_on:
        - "um_snmp"
    environment:
        - LDAP_ORGANISATION=Universidad de Murcia
        - LDAP_DOMAIN=um.es
        - LDAP_ADMIN_PASSWORD=um_password
        - HOSTNAME=ldap.um.es #Bug
        - LDAP_TLS=true
        - LDAP_TLS_CRT_FILENAME=ldap-cert.pem
        - LDAP_TLS_KEY_FILENAME=ldap-key.pem
        - LDAP_TLS_CA_CRT_FILENAME=um.pem
        - LDAP_TLS_ENFORCE=false
    volumes:
        - um-certs-ldap:/container/service/slapd/assets/certs
    networks:
        red1:
            aliases:
                - ldap.um.es
            ipv4_address: 192.168.251.6

  um_pc1:
    build: ./um/pc1/
    depends_on:
        - "um_snmp"
    networks:
        red1:
            ipv4_address: 192.168.251.20

  um_voip: #VoIP
    build: ./um/voip/
    hostname: voip
    domainname: um.es
    depends_on:
        - "um_snmp"
    volumes:
        - um-certs-voip:/certs
        - lego_ca:/ca_ssl
    networks:
        red1:
            aliases:
                - voip.um.es
            ipv4_address: 192.168.251.2

# Org2 #####################################

  upm_ca:
    build: ./um/ca/
    hostname: ca
    domainname: upm.es
    volumes:
        - upm-certs:/certs
    network_mode: none

  upm_crl:
    image: halverneus/static-file-server
    hostname: crl
    domainname: upm.es
    environment:
        - PORT=80
    volumes:
        - lego_ca:/web
    networks:
        red2:
            aliases:
                - crl.upm.es
            ipv4_address: 192.168.252.99

  upm_snmp:
    build: ./upm/snmp/
    hostname: snmp
    domainname: upm.es
    networks:
        red2:
            aliases:
                - snmp.upm.es
            ipv4_address: 192.168.252.100
            
  upm_voip: #VoIP
    build: ./upm/voip/
    hostname: voip
    domainname: upm.es
    depends_on:
        - "upm_openldap"
        - "upm_snmp"
    volumes:
        - upm-certs-voip:/certs
        - lego_ca:/ca_ssl
    networks:
        red2:
            aliases:
                - voip.upm.es
            ipv4_address: 192.168.252.2

  upm_radius:
    build: ./upm/radius/
    hostname: radius
    domainname: upm.es
    depends_on:
        - "upm_snmp"
    networks:
        red2:
            aliases:
                - radius.upm.es
            ipv4_address: 192.168.252.3

  upm_openldap:
    build: ./upm/openldap/
    hostname: ldap
    domainname: upm.es
    depends_on:
        - "upm_snmp"
    environment:
        - LDAP_ORGANISATION=Universidad Politecnica de Madrid
        - LDAP_DOMAIN=upm.es
        - LDAP_ADMIN_PASSWORD=upm_password
        - HOSTNAME=ldap.upm.es #Bug
        - LDAP_TLS=true
        - LDAP_TLS_CRT_FILENAME=ldap-cert.pem
        - LDAP_TLS_KEY_FILENAME=ldap-key.pem
        - LDAP_TLS_CA_CRT_FILENAME=upm.pem
        - LDAP_TLS_ENFORCE=false
    volumes:
        - upm-certs-ldap:/container/service/slapd/assets/certs
    networks:
        red2:
            aliases:
                - ldap.upm.es
            ipv4_address: 192.168.252.6

# PERSISTENCE ###############################

volumes:
    lego_ca:
        external:
            name: "lego_ca"
    
    
    um-certs:
        external:
            name: "um-certs"
    um-certs-voip:
        external:
            name: "um-certs-voip"
    um-certs-owncloud:
        external:
            name: "um-certs-owncloud"
    um-certs-ldap:
        external:
            name: "um-certs-ldap"
            
    upm-certs:
        external:
            name: "upm-certs"
    upm-certs-voip:
        external:
            name: "upm-certs-voip"
    upm-certs-owncloud:
        external:
            name: "upm-certs-owncloud"
    upm-certs-ldap:
        external:
            name: "upm-certs-ldap"

# NETWORKS ################################
networks:
  red1:
    driver: bridge
    driver_opts:
            com.docker.network.bridge.enable_icc: "true"
    ipam:
     config:
       - subnet: 192.168.251.0/24

  red2:
    driver: bridge
    driver_opts:
            com.docker.network.bridge.enable_icc: "true"
    ipam:
     config:
       - subnet: 192.168.252.0/24
