version: '3'
services:

# Org1 #####################################
  um_server:
    hostname: um_server
    build: ./um/server/
    volumes:
        - um-certs:/certs
    networks:
        red1:
            ipv4_address: 192.168.251.100

  um_pc1:
    hostname: um_pc1
    build: ./um/pc1/
    depends_on:
        - "um_server"
    networks:
        red1:
            ipv4_address: 192.168.251.20

  um_voip: #VoIP
    hostname: um_voip
    build: ./um/voip/
    depends_on:
        - "um_server"
    networks:
        red1:
            ipv4_address: 192.168.251.2

# Org2 #####################################
  org2_n1:
    build: ./org2/
    networks:
        red2:
            ipv4_address: 192.168.252.100

            
networks:
  red1:
    driver: bridge
    driver_opts:
            com.docker.network.bridge.enable_icc: "true"
    ipam:
     config:
       - subnet: 192.168.251.0/24

  red2:
    driver: bridge
    driver_opts:
            com.docker.network.bridge.enable_icc: "true"
    ipam:
     config:
       - subnet: 192.168.252.0/24


volumes:
    um-certs:
    upm-certs:
