version: '3'
services:

# Org1 #####################################
  um_server:
    hostname: um_server
    build: ./um/server/
    volumes:
        - um-certs:/certs
    networks:
        red1:
            ipv4_address: 192.168.251.100

  um_radius:
    hostname: um_radius
    build: ./um/radius/
    depends_on:
        - "um_server"
    networks:
        red1:
            ipv4_address: 192.168.251.3

  um_pc1:
    hostname: um_pc1
    build: ./um/pc1/
    depends_on:
        - "um_server"
    networks:
        red1:
            ipv4_address: 192.168.251.20

  um_voip: #VoIP
    hostname: um_voip
    build: ./um/voip/
    depends_on:
        - "um_server"
    networks:
        red1:
            ipv4_address: 192.168.251.2

# Org2 #####################################
  upm_voip: #VoIP
    hostname: upm_voip
    build: ./upm/voip/
    networks:
        red2:
            ipv4_address: 192.168.252.2

# PERSISTENCE ###############################

volumes:
    um-certs:
        external:
            name: "um-certs"
    upm-certs:
        external:
            name: "upm-certs"

# NETWORKS ################################
networks:
  red1:
    driver: macvlan
    driver_opts:
            parent: enp1s0.3
    ipam:
     config:
       - subnet: 192.168.251.0/24

  red2:
    driver: macvlan
    driver_opts:
            parent: enp1s0.4
    ipam:
     config:
       - subnet: 192.168.252.0/24
