version: '3'
services:

# Org1 #####################################
  org1_server:
    build: ./org1/server/
    networks:
        red1:
            ipv4_address: 192.168.251.100

  org1_pc1:
    build: ./org1/pc1/
    networks:
        red1:
            ipv4_address: 192.168.251.20

  org1_voip: #VoIP
    build: ./org1/voip/
    networks:
        red1:
            ipv4_address: 192.168.251.2

# Org2 #####################################
  org2_n1:
    build: ./org2/
    networks:
        red2:
            ipv4_address: 192.168.252.100

            
networks:
  red1:
    driver: bridge
    driver_opts:
            com.docker.network.bridge.enable_icc: "true"
    ipam:
     config:
       - subnet: 192.168.251.0/24

  red2:
    driver: bridge
    driver_opts:
            com.docker.network.bridge.enable_icc: "true"
    ipam:
     config:
       - subnet: 192.168.252.0/24
