version: '3'
services:
  org1_n1:
    build: ./org1/
    networks:
        red1:
            ipv4_address: 192.168.251.100
    
  org2_n1:
    build: ./org2/
    networks:
        red2:
            ipv4_address: 192.168.252.100

  ccalculo_n1: #Centro de calculo
    build: ./ccalculo/n1/
    networks:
        red3:
            ipv4_address: 192.168.253.100


networks:
  red1:
    driver: bridge
    driver_opts:
            com.docker.network.bridge.enable_icc: "true"
    ipam:
     config:
       - subnet: 192.168.251.0/24

  red2:
    driver: bridge
    driver_opts:
            com.docker.network.bridge.enable_icc: "true"
    ipam:
     config:
       - subnet: 192.168.252.0/24

  red3: #Centro de Calculo
    driver: bridge
    driver_opts:
            com.docker.network.bridge.enable_icc: "true"
    ipam:
     config:
       - subnet: 192.168.253.0/24
